apiVersion: argoproj.io/v1alpha1
kind: Apllication
metadata:
  name: my-sample-app
  namespace: argocd
spec:
  destination: 
    name: ''
    namespace: my-sample-app
    server: 'https://kubernetes.default.svc'
  project: default
  
  source:
    repoURL: 'https://github.com/your-org/my-sample-app.git'
    targetRevision: 'main' 
    path: 'charts/my-sample-app' 
    helm:
      releaseName: my-sample-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
