apiVersion: argoproj.io/v1alpha1
kind: Apllication
metadata:
  name: sample-node-app
  namespace: argocd
spec:
  destination: 
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  
  source:
    repoURL: 'https://github.com/skswami91/k8s-manifests-2025.git'
    targetRevision: 'main' 
    path: 'sample-node-app' 
  project: default  
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
