apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-sample-app.name" . }}
  labels:
    app: {{ include "my-sample-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "my-sample-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                    
